#HomeLab Main Light
- alias: Turn on HomeLab main_light when there is movement
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgms001_zw5_motion_sensor_burglar
    to: '8'
  action:
    service: homeassistant.turn_on
    entity_id: switch.qubino_goap_zmnhadx_flush_1_relay_switch

- alias: Turn off HomeLab main_light when there is movement
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgms001_zw5_motion_sensor_burglar
    to: '0'
    for:
      minutes: 30
  action:
    service: homeassistant.turn_off
    entity_id: switch.qubino_goap_zmnhadx_flush_1_relay_switch

- alias: Turn off HomeLab main_light when there is movement
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgms001_zw5_motion_sensor_burglar
    to: '254'
    for:
      minutes: 30
  action:
    service: homeassistant.turn_off
    entity_id: switch.qubino_goap_zmnhadx_flush_1_relay_switch

#HomeLab Desk Light
- alias: Turn on HomeLab desk_light when there is movement
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgms001_zw5_motion_sensor_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.sjons_macbook_pro
        state: home
  action:
    service: homeassistant.turn_on
    entity_id: switch.homelab_desk_light

- alias: Turn off HomeLab desk_light 10 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgms001_zw5_motion_sensor_burglar
    to: '0'
    for:
      minutes: 30
  action:
    service: homeassistant.turn_off
    entity_id: switch.homelab_desk_light

#HomeLab Audio System
- alias: Turn on HomeLab audio speakers when media_player.volumio state is playing
  trigger:
    platform: state
    entity_id: media_player.openhome_359cb6e2_c592_e30b_da2c_b827eb55c248
    to: 'playing'
  action:
    service: homeassistant.turn_on
    entity_id: switch.tkb_home_tz68_on_off_switch_socket_switch

- alias: Turn off HomeLab audio speakers when media_player.volumio state is idle
  trigger:
    platform: state
    entity_id: media_player.openhome_359cb6e2_c592_e30b_da2c_b827eb55c248
    to: 'idle'
    for:
      minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: switch.tkb_home_tz68_on_off_switch_socket_switch

- alias: Turn off HomeLab audio speakers when media_player.volumio state is paused
  trigger:
    platform: state
    entity_id: media_player.openhome_359cb6e2_c592_e30b_da2c_b827eb55c248
    to: 'paused'
    for:
      minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: switch.tkb_home_tz68_on_off_switch_socket_switch

#Serre Room Ambilight
- alias: Turn on Serre Ambilight at given time
  trigger:
    platform: time
    at: '18:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.serre_ambilight

- alias: Turn off Serre Ambilight at given time
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.serre_ambilight

#maybe also set on startup so it configures after a reboot

# - alias: 'Set theme at startup'
#   trigger:
#     platform: homeassistant
#     event: start
#   action:
#     service: frontend.set_theme
#     data:
#       name: Dark & Green (Theme Name)

- alias: 'Set HA theme for day and night'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            clear - day
          {% else %}
            clear - night
          {% endif %}

#Turn on Bed Lights Right and Left
#TODO: change the enity id to the id of a group bed lights master bedroom and witch the entire group on
- alias: Turn on Bed Lights
  trigger:
    platform: time
    at: '21:00:00'
  action:
    service: light.turn_on
    data:
      brightness: 75
      entity_id:
        - light.dimmable_light_bed_side_dani
        - light.dimmable_light_bed_side_sjon

#Turn on living room ambilights @ 75%
- alias: Turn on living room ambilights 75%
  trigger:
    platform: time
    at: '17:30:00'
  action:
    service: light.turn_on
    data:
      brightness: 175
      entity_id:
        - light.dimmable_light_tv
        - light.dimmable_light_couch

#Turn on living room ambilights @ 30%
- alias: Turn on living room ambilights 30%
  trigger:
    platform: time
    at: '20:30:00'
  action:
    service: light.turn_on
    data:
      brightness: 75
      entity_id:
        - light.dimmable_light_tv
        - light.dimmable_light_couch
