#############################################################################
#       HOME ASSISTANT CONFIG                                               #
#############################################################################
homeassistant:
  name: home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: !secret home_timezone
  unit_system: !secret home_unitsystem
  customize: !include customize.yaml
  #https://www.home-assistant.io/docs/configuration/packages/
  packages: !include_dir_merge_named packages/

##############################################################################
#       FRONT-END CUSTOMS                                                    #
##############################################################################

frontend:
  themes: !include_dir_merge_named themes/

##############################################################################
#       ENABLES                                                              #
##############################################################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

rpi_gpio:

map:

sun:

# Text to speech
tts:
  - platform: google_translate

##############################################################################
#       TESTING                                                              #
##############################################################################

#python_script:
# hello_mqtt:
#   topic: some_mqtt/topic/here

# input_boolean:
#   activate_relax_scene:
#     name: Activate relax scene
#     icon: mdi:wine
#     initial: off

##############################################################################
#       INCLUDES                                                             #
##############################################################################
remote_homeassistant: !include remote_homeassistant.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
