###################################################
#               home-hallway-lights               #
###################################################
- alias: Turn on home-hallway-lights when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.presence_2
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.fibaro_system_fgd212_dimmer_2_level_2

- alias: Turn off home-hallway-lights 30 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.presence_2
    to: 'off'
    # for:
    #   minutes: 30
  action:
    service: homeassistant.turn_off
    entity_id: light.fibaro_system_fgd212_dimmer_2_level_2
