###################################################
#               HomeLab Audio System              #
###################################################

- alias: Turn on HomeLab audio speakers 10 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgms001_zw5_motion_sensor_burglar
    to: '8'
  action:
    service: homeassistant.turn_on
    entity_id: switch.rf_homelab_speakers

- alias: Turn off HomeLab audio speakers 10 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgms001_zw5_motion_sensor_burglar
    to: '0'
    for:
      minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: switch.rf_homelab_speakers
